num1 = input('Hello, welcome to the sum, difference, product and quotient calculator! Please type the first number. ')
num2 = input('Please type the second number. ')
sum = int(num1) + int(num2)
diff = int(num1) - int(num2)
quotient = int(num1) / int(num2)
product = int(num1) * int(num2)
print('Sum:' + str(sum))
print('Difference: ' + str(diff))
print('Product: ' + str(product))
print('Quotient: ' + str(quotient))
print('''
Thanks for using this calculator! ♥-♥  ''')
